# Generated by Django 5.2.5 on 2025-08-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description. Leave blank to use meta_description.', max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title. Leave blank to use meta_title.', max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 chars). Leave blank to auto-generate.', max_length=160),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 60 chars). Leave blank to auto-generate from title.', max_length=60),
        ),
    ]
