# Generated by Django 5.2.5 on 2025-08-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_og_description_project_og_title_and_more'),
    ]

    operations = [
    ]
