# Generated by Django 5.2.5 on 2025-08-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='services_hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for services page', upload_to='site/heroes/'),
        ),
    ]
