# Generated by Django 5.2.5 on 2025-08-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_services_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField(help_text='Brief biography')),
                ('detailed_bio', models.TextField(blank=True, help_text='Detailed biography for profile page')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('photo', models.ImageField(help_text='Professional headshot', upload_to='team/')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for profile page', upload_to='team/covers/')),
                ('years_experience', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('specializations', models.TextField(blank=True, help_text='Areas of specialization, one per line')),
                ('education', models.TextField(blank=True, help_text='Educational background')),
                ('certifications', models.TextField(blank=True, help_text='Professional certifications, one per line')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
