# Generated by Django 5.2.5 on 2025-08-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for about page', upload_to='site/heroes/'),
        ),
    ]
