# Generated by Django 5.2.5 on 2025-08-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_about_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='blog_hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for blog page', upload_to='site/heroes/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='careers_hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for careers page', upload_to='site/heroes/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for contact page', upload_to='site/heroes/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for projects page', upload_to='site/heroes/'),
        ),
    ]
