# Generated by Django 5.2.5 on 2025-08-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_blog_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='blog_url',
            field=models.URLField(blank=True, help_text='Blog URL (can be external)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='get_in_touch_text',
            field=models.CharField(default='Get in Touch', help_text='Text for the get in touch button', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Main hero background image', upload_to='site/heroes/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_card_image',
            field=models.ImageField(blank=True, help_text='Hero section card image', upload_to='site/heroes/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Skyline Ghana Constructions is a leading name in construction and design, transforming visions into reality with precision, innovation, and a commitment to quality.', help_text='Hero subtitle/description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Building the Future, Block by Block.', help_text='Main hero title', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_blog_in_top_nav',
            field=models.BooleanField(default=True, help_text='Show blog link in top navigation'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='top_navbar_email',
            field=models.EmailField(blank=True, default='info@skylineghana.com', help_text='Email displayed in top navbar', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='top_navbar_phone',
            field=models.CharField(blank=True, default='+233 24 123 4567', help_text='Phone number displayed in top navbar', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
    ]
