# Generated by Django 5.2.5 on 2025-08-15 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_blog_url_sitesettings_get_in_touch_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='site/about/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'About Section Image',
                'verbose_name_plural': 'About Section Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
