# Generated by Django 5.2.5 on 2025-08-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aboutsectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_company_image',
            field=models.ImageField(blank=True, help_text='Company image for About page content section', upload_to='site/content/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_team_member_image',
            field=models.ImageField(blank=True, help_text='Default image for team members without photos', upload_to='site/defaults/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_testimonial_image',
            field=models.ImageField(blank=True, help_text='Default image for testimonials without photos', upload_to='site/defaults/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_service_1_image',
            field=models.ImageField(blank=True, help_text='Background image for first featured service card (Construction)', upload_to='site/services/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_service_2_image',
            field=models.ImageField(blank=True, help_text='Background image for second featured service card (Design)', upload_to='site/services/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_service_3_image',
            field=models.ImageField(blank=True, help_text='Background image for third featured service card (Materials)', upload_to='site/services/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='why_choose_us_image',
            field=models.ImageField(blank=True, help_text="Image for 'Why Choose Us' section on homepage", upload_to='site/content/'),
        ),
    ]
