# Generated by Django 5.2.5 on 2025-08-17 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_about_company_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='site/homepage_carousel/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_carousel_images', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Homepage Carousel Image',
                'verbose_name_plural': 'Homepage Carousel Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
