# Generated by Django 5.2.5 on 2025-08-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_homepagecarouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='join_team_left_image',
            field=models.ImageField(blank=True, help_text="Left side image for 'Join the Team' section on homepage", upload_to='site/content/'),
        ),
    ]
