# Generated by Django 5.2.5 on 2025-08-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_join_team_left_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude for Google Maps', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude for Google Maps', max_digits=11, null=True),
        ),
    ]
