# Generated by Django 5.2.5 on 2025-08-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_latitude_sitesettings_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='client_satisfaction',
            field=models.PositiveIntegerField(default=98, help_text='Client satisfaction percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_completed',
            field=models.PositiveIntegerField(default=500, help_text='Total number of projects completed'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='square_feet_built',
            field=models.PositiveIntegerField(default=1000000, help_text='Total square feet built'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='years_experience',
            field=models.PositiveIntegerField(default=25, help_text='Years of experience in construction'),
        ),
    ]
