# Generated by Django 5.2.5 on 2025-08-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for service page', upload_to='services/heroes/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for category page', upload_to='services/heroes/'),
        ),
    ]
