# Generated by Django 5.2.5 on 2025-08-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_hero_image_servicecategory_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title/caption for the image', max_length=200)),
                ('image', models.ImageField(help_text='Image for the service page', upload_to='services/page_images/')),
                ('description', models.TextField(blank=True, help_text='Optional description of the project/image')),
                ('location', models.CharField(blank=True, help_text='Project location (optional)', max_length=100)),
                ('completion_year', models.PositiveIntegerField(blank=True, help_text='Year completed (optional)', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this image prominently')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_images', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Page Image',
                'verbose_name_plural': 'Service Page Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
