# Generated by Django 5.2.5 on 2025-08-17 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicepageimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepageimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Service Category Image', 'verbose_name_plural': 'Service Category Images'},
        ),
        migrations.RemoveField(
            model_name='servicepageimage',
            name='service',
        ),
        migrations.AddField(
            model_name='servicepageimage',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='page_images', to='services.servicecategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicepageimage',
            name='image',
            field=models.ImageField(help_text='Image for the service category page', upload_to='services/page_images/'),
        ),
    ]
